# @package _group_
task:
  _name: translation_lev
  data: /content/drive/MyDrive/NLP_project_1/iwslt14.tokenized.de-en 
  source_lang: de
  target_lang: en
  noise: random_mask
criterion:
  _name: rl_loss
  sentence_level_metric: CHRF
model:
  _name: cmlm_transformer_base
  share_decoder_input_output_embed: true
  decoder:
    learned_pos: true
  encoder:
    learned_pos: true
  length_loss_factor: 0.01
optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
lr_scheduler:
  _name: inverse_sqrt
  warmup_updates: 200
  warmup_init_lr: 1e-07
dataset:
  max_tokens: 8192
  validate_interval_updates: 50
optimization:
  lr: [0.0005]
  update_freq: [8]
  max_update: 5000
  stop_min_lr: 1e-09
checkpoint:
  no_epoch_checkpoints: false
common:
  log_format: simple
  log_interval: 10
  tensorboard_logdir: /content/drive/MyDrive/NLP_project_1
